version: '3'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: $POG_PG_USERNAME
      POSTGRES_PASSWORD: $POG_PG_PASSWORD
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
