version: '2'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: $POG_PG_USERNAME
      POSTGRES_PASSWORD: $POG_PG_PASSWORD
  web:
    build: .
    env_file: .env
    command: bash -c "rm /myapp/tmp/pids/server.pid ; bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db
